config/routes.rb
Rails.application.routes.draw do

  resources :panding_logs

  resources :products#, except: [:destroy]

  resources :order_details

  resources :customers, except: [:destroy]

  resources :orders do
    member do
      post 'to_pand'
      post 'pand_pass'
      post 'pand_back'
      post 'to_deliver'
      post 'to_cancel'
      get 'print_order'
      get 'fancybox_show'
    end
  end

  root 'welcome#index'

  resources :users, only: [:index, :show, :edit, :update, :new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders

  validates_presence_of :name
  validates_presence_of :address
  validates_uniqueness_of :name

  def show_text
    "#{name} - #{phone || '无联系电话'} - #{consignee || '无收件人'}"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result(distinct: true).page(params[:page])
    # @customers = Customer.page(params[:page])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :phone, :consignee)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, html: {class: "form-horizontal"}) do |f| %>
  <% if @customer.errors.any? %>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <div class="alert alert-warning alert-danger" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4><%= @customer.errors.count %>个错误导致保存失败:</h4>
          <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
  <% end %>

  <div class="form-group">
    <label for="customer_name" class="col-sm-2 control-label">客户名称</label>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="customer_address" class="col-sm-2 control-label">客户地址</label>
    <div class="col-sm-8">
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="customer_phone" class="col-sm-2 control-label">联系电话</label>
    <div class="col-sm-8">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="customer_consignee" class="col-sm-2 control-label">收件人</label>
    <div class="col-sm-8">
      <%= f.text_field :consignee, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>更新客户信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '客户详情', @customer, class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '返回客户列表', customers_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>客户信息列表</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '新建客户', new_customer_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= search_form_for @q, class: "form-inline", html: {style: "margin-bottom: 10px;"} do |f| %>
      <div class="form-group">
        <label class="sr-only" for="q_name_cont"></label>
        <%= f.search_field :name_cont, class: "form-control", placeholder: "客户名称" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_address_cont"></label>
        <%= f.search_field :address_cont, class: "form-control", placeholder: "客户地址" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_phone_cont"></label>
        <%= f.search_field :phone_cont, class: "form-control", placeholder: "客户电话" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_consignee_cont"></label>
        <%= f.search_field :consignee_cont, class: "form-control", placeholder: "收件人" %>
      </div>

      <button type="submit" class="btn btn-primary">查询</button>
      <button type="submit" id="search_reset" class="btn btn-warning">重置</button>
    <% end %>

    <table class="table table-condensed table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>客户名称</th>
          <th>客户地址</th>
          <th>联系电话</th>
          <th>收件人</th>
          <th>操作</th> 
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |u| %>
          <tr>
            <td><%= u.id %></td>
            <td><%= u.name %></td>
            <td><%= u.address %></td>
            <td><%= u.phone %></td>
            <td><%= u.consignee %></td>
            <td>
              <%= link_to "客户详情", customer_path(u), class: "btn btn-default" %>
              <%= link_to "编辑客户", edit_customer_path(u), class: "btn btn-default" %>
            </td> 
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @customers %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
</script>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>创建客户信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '返回客户列表', customers_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>客户信息详情</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '编辑客户', edit_customer_path(@customer), class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '返回客户列表', customers_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <div class="jumbotron">
      <table class="table">
        <tr>
          <td>用户名称：</td>
          <td><%= @customer.name %></td>
        </tr>

        <tr>
          <td>客户地址：</td>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <td>联系电话：</td>
          <td><%= @customer.phone %></td>
        </tr>

        <tr>
          <td>收件人：</td>
          <td><%= @customer.consignee %></td>
        </tr>
      </table>
    </div>

  </div>
  <div class="col-md-1"></div>
</div>