config/routes.rb
Rails.application.routes.draw do

  resources :panding_logs

  resources :products#, except: [:destroy]

  resources :order_details

  resources :customers, except: [:destroy]

  resources :orders do
    member do
      post 'to_pand'
      post 'pand_pass'
      post 'pand_back'
      post 'to_deliver'
      post 'to_cancel'
      get 'print_order'
      get 'fancybox_show'
    end
  end

  root 'welcome#index'

  resources :users, only: [:index, :show, :edit, :update, :new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM

  # validates :code, presence: true
  validates :customer_id, presence: true
  validates :totle_amount, presence: true
  validates :totle_sum, presence: true
  validates :saleman, presence: true

  has_many :order_details, dependent: :destroy
  has_many :pandding_logs, dependent: :destroy
  belongs_to :customer
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  accepts_nested_attributes_for :order_details, :allow_destroy => true

  before_create :set_code

  def set_code
    prefix = Time.now.strftime('%Y%m')
    last_serial = (Order.where("code like ?", "#{prefix}%").last.code[6, 4].to_i rescue 0)
    serial = (last_serial + 1).to_s.rjust(4, "0") 
    self.code = prefix + serial
  end

  STATE_HASH = {
    creating: "待提交",
    panding: "审核中",
    passed: "审核通过",
    delivered: "已发货",
    cancelled: "作废"
  }.freeze

  def state_cn
    STATE_HASH[self.aasm_state.to_sym]
  end

  aasm do
    state :creating, :initial => true
    state :panding
    state :passed
    state :delivered
    state :cancelled

    # 提交审核
    event :submit do
      transitions :from => :creating, :to => :panding
    end

    # 审核通过
    event :pass, :after => :update_pass_time do
      transitions :from => :panding, :to => :passed
    end

    # 审核不通过
    # 必须填写驳回日志，通过事务处理
    event :reject do
      transitions :from => [:panding, :passed], :to => :creating
    end

    # # 物流驳回
    # event :shipment_reject do
    #   transitions :from => :passed, :to => :creating
    # end

    # 出货
    event :deliver do
      transitions :from => :passed, :to => :delivered, :guard => :got_shipment_code?
    end

    # 作废
    event :cancel do
      transitions :from => :creating, :to => :cancelled
    end
  end

  def got_shipment_code?
    self.shipment_code.present?
  end

  def update_pass_time
    self.update_attribute("pass_time", Time.now)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [ :show, :print_order, :edit, :update, :destroy,
                                    :to_pand, :pand_pass, :pand_back,
                                    :to_deliver, :to_cancel, :fancybox_show ]
  before_action(only: [:new, :create, :edit, :update]) { can_access("前台客服") }
  before_action(only: :destroy) { can_access("财务部门") }

  # GET /orders
  # GET /orders.json
  def index
    @q = Order.ransack(params[:q])
    @orders = @q.result(distinct: true).includes(:customer).page(params[:page])
    # @orders = Order.page(params[:page])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  def fancybox_show
    render layout: "content"
  end

  def print_order
    render layout: "print"
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.creator = current_user
    @order.order_details.build
  end

  # GET /orders/1/edit
  def edit
    unless @order.may_submit?
      flash[:notice] = "目前该订单的状态不允许进行编辑操作！"
      redirect_to '/' 
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: '订单删除成功！' }
      format.json { head :no_content }
    end
  end

  # 提交审核
  def to_pand
    raise "当前用户不能进行这个操作！" unless current_user.is?("前台客服 系统管理员")
    raise "不能提交审核，请检查该记录的状态！" unless @order.may_submit?
    if @order.submit!
      render json: {msg: "提交审核操作成功！", state: @order.state_cn}
    else
      raise "发生异常，操作失败！"
    end
  rescue Exception => e
    render json: {msg: "#{e}"}.to_json
  end

  # 审核通过
  def pand_pass
    raise "当前用户不能进行这个操作！" unless current_user.is?("财务部门 系统管理员")
    raise "不能审核，请检查该记录的状态！" unless @order.may_pass?
    if @order.pass!
      render json: {msg: "审核通过操作成功！", state: @order.state_cn}
    else
      raise "发生异常，操作失败！"
    end
  rescue Exception => e
    render json: {msg: "#{e}"}.to_json
  end

  # 审核不通过
  def pand_back
    raise "当前用户不能进行这个操作！" unless current_user.is?("财务部门 仓库 系统管理员")
    raise "不能审核，请检查该记录的状态！" unless @order.may_reject?
    raise "审核驳回理由不能为空！" if params[:reason].blank?
    ActiveRecord::Base.transaction do
      PanddingLog.create!(order: @order, user: current_user, reason: params[:reason])
      if @order.reject!
        render json: {msg: "审核驳回操作成功！", state: @order.state_cn}
      else
        raise "发生异常，操作失败！"
      end
    end
  rescue Exception => e
    render json: {msg: "#{e}"}.to_json
  end

  # 发货
  def to_deliver
    raise "当前用户不能进行这个操作！" unless current_user.is?("仓库 系统管理员")
    raise "物流编号不能为空！" if params[:shipment_code].blank?
    @order.shipment_code = params[:shipment_code]
    raise "不能发货，请检查该记录的状态！" unless @order.may_deliver?
    if @order.deliver!
      render json: {msg: "发货操作成功！", state: @order.state_cn}
    else
      raise "发生异常，操作失败！"
    end
  rescue Exception => e
    render json: {msg: "#{e}"}.to_json
  end

  # 作废
  def to_cancel
    raise "当前用户不能进行这个操作！" unless current_user.is?("前台客服 系统管理员")
    raise "不能作废，请检查该记录的状态！" unless @order.may_cancel?
    if @order.cancel!
      render json: {msg: "作废操作成功！", state: @order.state_cn}
    else
      raise "发生异常，操作失败！"
    end
  rescue Exception => e
    render json: {msg: "#{e}"}.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:code, :customer_id, :totle_amount, :totle_sum, :inceptor, :saleman, :creator_id, :state, :order_details_attributes => [:id, :product_id, :amount, :discount, :sum, :_destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <div class="alert alert-warning alert-danger" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4><%= @order.errors.count %>个错误导致保存失败:</h4>
          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
  <% end %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 90px;"></th>
        <th></th>
        <th style="width: 70px;"></th>
        <th style="width: 70px;"></th>
        <th style="width: 70px;"></th>
        <th style="width: 90px;"></th>
        <th style="width: 70px;"></th>
      </tr>
    </thead>
    <tbody>
      
      <tr>
        <td colspan='1'>客户名称：</td>
        <td colspan='3'>
          <%= f.collection_select :customer_id, Customer.all, :id, :show_text, {:prompt => true}, {:class=>'combobox form-control'} %>
        </td>
        <td colspan='1'>编号：</td>
        <td colspan='2'>-</td>
      </tr>
      <tr>
        <td colspan='1'>客户地址：</td>
        <td colspan='3'><p id="address_ele"><%= @order.customer.address if @order.customer %></p></td>
        <td colspan='1'>时间：</td>
        <td colspan='2'>-</td>
      </tr>
      <tr>
        <td><%= link_to_add_association '添加', f, :order_details, class: "btn btn-primary", role: "button" %></td>
        <td>品名及规格</td>
        <td>单位</td>
        <td>数量</td>
        <td>价格</td>
        <td>折扣（％）</td>
        <td>金额</td>
      </tr>

      <%= f.fields_for :order_details do |f| %>
        <%= render "order_detail_fields", f: f %>
      <% end %>

      <tr>
        <td colspan='3'>数量合计</td>
        <td><%= f.number_field :totle_amount, class: "form-control", readonly: "readonly" %></td>
        <td colspan='3'></td>
      </tr>
      <tr>
        <td colspan='3'>金额合计</td>
        <td colspan='3'><p class="traditional_price"></p></td>
        <td>
          <div class="input-group">
            <span class="input-group-addon">¥</span>
            <%= f.text_field :totle_sum, class: "form-control", readonly: "readonly" %>
          </div>
        </td>
      </tr>
      <tr>
        <td>签收人：</td>
        <td>-</td>
        <td>业务员：</td>
        <td colspan='2'><%= f.text_field :saleman, class: "form-control" %></td>
        <td>制单：</td>
        <td>
          <%= @order.creator.name %>
          <%= f.hidden_field :creator_id, class: "form-control" %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="actions">
    <button type="submit" class="btn btn-default">提交</button>
  </div>

  <script type="text/javascript">
    $(document).ready(function(){
      // init
      var remove_button_amount = $("a.remove_fields").size();
      $('.combobox').combobox();
      check_to_hide_or_show_delete_link();
      $("tr.order_detail").each(function(){
        console.log($(this));
        update_detail_fields($(this));
      });
      // init

      $("form").on("change", "[name='order[customer_id]']", function(){
        $.ajax({
          type: "GET",
          url: "/customers/" + $(this).val() + ".json",
          success: function(data){  
            $("#address_ele").text(data.address);
          }
        });
      });

      $("form").on("change", "[name$='[product_id]']", function(){
        tr_node = $(this).parents("tr");
        update_detail_fields(tr_node);
      });

      function update_detail_fields (tr_node) {
        product_id = tr_node.find("[name$='[product_id]']").val();
        amount = tr_node.find("[name$='[amount]']");
        unit_node = tr_node.find(".unit_ele");
        price_node = tr_node.find(".price_ele");

        $.ajax({
          type: "GET",
          async:false,
          url: "/products/" + product_id + ".json",
          success: function(data){
            amount.val(1);
            unit_node.text(data.unit);
            price_node.text(data.price);
            update_detail_sum(price_node);
            update_total_amount();
          }
        });
      }

      $("form").on("change", "[name$='[amount]']", function(){
        update_detail_sum($(this));
        update_total_amount();
      });

      $("form").on("change", "[name$='[discount]']", function(){
        update_detail_sum($(this));
      });

      function update_detail_sum (node) {
        tr_node = node.parents("tr");
        price = parseFloat(tr_node.find(".price_ele").text());
        amount = tr_node.find("[name$='[amount]']").val();
        discount = tr_node.find("[name$='[discount]']").val();
        detail_sum_node = tr_node.find("[name$='[sum]']")
        // 计算方法需要再校验一下
        detail_sum = price * amount * discount / 100
        detail_sum_node.val(detail_sum);
        update_total_sum();
      }

      function update_total_sum () {
        totle_sum = 0
        $("[name$='[sum]']").each(function(){
          totle_sum += parseInt($(this).val());
        });
        $("#order_totle_sum").val(totle_sum);
        $(".traditional_price").text(convertCurrency(totle_sum));
      }

      function update_total_amount () {
        console.log("ready");
        totle_amount = 0
        $("[name$='[amount]']").each(function(){
          totle_amount += parseInt($(this).val());
        });

        // 减去删除的数量
        $("[name$='[_destroy]']").each(function(){
          if ($(this).val() == "1") {
            totle_amount -= 1;
          };
        });
        
        $("#order_totle_amount").val(totle_amount);
      }

      $("form a.add_fields").
      data("association-insertion-method", 'after').
      data("association-insertion-node", 'tr.order_detail:last');

      $('form')
        .on('cocoon:after-insert', function(e, insertedItem) {
          console.log("insert");
          combobox = insertedItem.find(".combobox");
          combobox.combobox();
          remove_button_amount += 1;
          check_to_hide_or_show_delete_link();
        }).on("cocoon:before-remove", function() {
          console.log("before remove");
        }).on("cocoon:after-remove", function() {
          console.log("remove");
          update_total_sum();
          update_total_amount();
          remove_button_amount -= 1;
          check_to_hide_or_show_delete_link();
        });

      function check_to_hide_or_show_delete_link () {
        if (remove_button_amount <= 1) {
          $('a.remove_fields').hide();
        } else {
          $('a.remove_fields').show();
        };

        if (remove_button_amount >= 12) {
          $('a.add_fields').hide();
        } else {
          $('a.add_fields').show();
        };
      }

    });
  </script>
<% end %>

app/views/orders/_order_detail_fields.html.erb
<tr class="order_detail">
  <td><%= link_to_remove_association '删除', f, { wrapper_class: 'order_detail', class: 'btn btn-danger', role: 'button', data: {confirm: '确认要删除这条订单详情吗？'} } %></td>
  <td><%= f.collection_select :product_id, Product.published, :id, :name, {:prompt => true}, {:class=>'combobox form-control'} %></td>
  <td><p class='unit_ele'></p></td>
  <td><%= f.text_field :amount, class: "form-control", style: "width: 60px;" %></td>
  <td><p class='price_ele'></p></td>
  <td><%= f.text_field :discount, class: "form-control", style: "width: 100%;" %></td>
  <td>
    <div class="input-group">
      <span class="input-group-addon">¥</span>
      <%= f.text_field :sum, class: "form-control", readonly: "readonly", style: "width: 150px;" %>
    </div>
  </td>
</tr>

app/views/orders/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>更新订单信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '订单详情', @order, class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '返回订单列表', orders_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
</script>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-10">
          <h3>订单信息列表</h3>
        </div>
        <div class="col-md-2" style='text-align: right;'>
          <% if can_access("前台客服") %>
            <%= link_to '新建订单', new_order_path, class: "btn btn-cs", style: "margin-top: 20px;" %>
          <% end %>
        </div>
      </div>
    </div>

    <%= search_form_for @q, class: "form-inline", html: {style: "margin-bottom: 10px;"} do |f| %>
      <div class="form-group">
        <label class="sr-only" for="q_code_cont"></label>
        <%= f.search_field :code_cont, class: "form-control", placeholder: "订单编号" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_customer_name_cont"></label>
        <%= f.search_field :customer_name_cont, class: "form-control", placeholder: "客户名称" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_pass_time_gteq"></label>
        <%= f.search_field :pass_time_gteq, class: "form-control datetimepicker4", placeholder: "审核通过起始日期" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_pass_time_lteq"></label>
        <%= f.search_field :pass_time_lteq, class: "form-control datetimepicker4", placeholder: "审核通过结束日期" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_pass_time_lteq"></label>
        <%= f.select :aasm_state_eq, options_for_select(Order::STATE_HASH.invert, @q.aasm_state_eq), {include_blank: "请选择状态"}, {:class => 'form-control'} %>
      </div>

      <button type="submit" class="btn btn-primary">查询</button>
      <button type="submit" id="search_reset" class="btn btn-warning">重置</button>
    <% end %>


    <table class="table table-condensed table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>订单编号</th>
          <th>客户名称</th>
          <th>客户地址</th>
          <th>数量合计</th>
          <th>金额合计</th>
          <th>签收人</th>
          <th>业务员</th>
          <th>制单员</th>
          <th>订单状态</th>
          <th>操作</th> 
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |u| %>
          <tr>
            <td><%= u.id %></td>
            <td><%= u.code %></td>
            <td><%= u.customer.name if u.customer %></td>
            <td><%= u.customer.address if u.customer %></td>
            <td><%= u.totle_amount %></td>
            <td><%= u.totle_sum %></td>
            <td><%= u.inceptor %></td>
            <td><%= u.saleman %></td>
            <td><%= u.creator.name if u.creator %></td>
            <td class="state_<%= u.id %>"><%= u.state_cn %></td>
            <td>
              <%= link_to "订单详情", fancybox_show_order_path(u), class: "btn btn-default fancybox fancybox.iframe", target: "_blank" %>
              
              <% if u.may_submit? && can_access("前台客服") %>
                <%= link_to "编辑订单", edit_order_path(u), class: "btn btn-cs" %>
                <button type="button" class="btn btn-cs to_pand" p-id="<%= u.id %>">提交审核</button>
              <% end %>
              <% if u.panding? && can_access("财务部门") %>
                <button type="button" class="btn btn-fa pand_pass" p-id="<%= u.id %>">审核通过</button>
                <button type="button" class="btn btn-fa pand_back" p-id="<%= u.id %>">审核驳回</button>
              <% end %>
              <% if u.passed? && can_access("仓库") %>
                <button type="button" class="btn btn-stm to_deliver" p-id="<%= u.id %>">发货</button>
                <button type="button" class="btn btn-stm pand_back" p-id="<%= u.id %>">物流驳回</button>
              <% end %>
              <% if u.delivered? && can_access("仓库") %>
                <%= link_to "打印", print_order_order_path(u), id: "print_#{u.id}", class: "btn btn-stm", target: "_blank", style:"color: #FFF;" %>
              <% end %>
              <% if u.may_cancel? && can_access("前台客服") %>
                <button type="button" class="btn btn-cs to_cancel" p-id="<%= u.id %>">作废</button>
              <% end %>
              <% if can_access("财务部门") %>
                <%= link_to "删除订单", u, method: :delete, data: { confirm: '确定要删除此订单吗？'}, class: "btn btn-cs" %>
              <% end %>
            </td> 
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
</script>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>创建订单信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '返回订单列表', orders_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
</script>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>订单信息详情</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <% if @order.may_submit? && can_access("前台客服") %>
            <%= link_to "编辑订单", edit_order_path(@order), class: "btn btn-cs", style: "margin-top: 20px;" %>
          <% end %>
          <%= link_to '返回订单列表', orders_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <div class="jumbotron">
      <table class="table table-bordered">
        <tr>
          <td colspan='7'>出货单</td>
        </tr>
        <tr>
          <td colspan='7'>上海玺爱商贸有限公司 电话：021-61363281</td>
        </tr>
        <tr>
          <td colspan='1'>客户名称：</td>
          <td colspan='3'><%= @order.customer.name if @order.customer %></td>
          <td colspan='1'>编号：</td>
          <td colspan='2'><%= @order.code %></td>
        </tr>
        <tr>
          <td colspan='1'>客户地址：</td>
          <td colspan='3'><%= @order.customer.address if @order.customer %></td>
          <td colspan='1'>时间：</td>
          <td colspan='2'><%= @order.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <td></td>
          <td>品名及规格</td>
          <td>单位</td>
          <td>数量</td>
          <td>价格</td>
          <td>折扣（％）</td>
          <td>金额</td>
        </tr>
        <% @order.order_details.each_with_index do |d, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= d.product.name if d.product %></td>
            <td><%= d.product.unit if d.product %></td>
            <td><%= d.amount %></td>
            <td><%= d.product.price if d.product %></td>
            <td><%= d.discount %></td>
            <td><%= d.sum %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan='3'>数量合计</td>
          <td><%= @order.totle_amount %></td>
          <td colspan='3'></td>
        </tr>
        <tr>
          <td colspan='3'>金额合计</td>
          <td colspan='3'><p class="traditional_price"></p></td>
          <td><%= @order.totle_sum %></td>
        </tr>
        <tr>
          <td>签收人：</td>
          <td colspan='2'></td>
          <td>业务员：</td>
          <td><%= @order.saleman %></td>
          <td>制单：</td>
          <td><%= @order.creator.name if @order.creator %></td>
        </tr>
      </table>

      <div style='text-align: right;'>
        <div class="btn-group" role="group">
          <% if @order.may_submit? && can_access("前台客服") %>
            <button type="button" class="btn btn-cs to_pand" p-id="<%= @order.id %>">提交审核</button>
          <% end %>
          <% if @order.panding? && can_access("财务部门") %>
            <button type="button" class="btn btn-fa pand_pass" p-id="<%= @order.id %>">审核通过</button>
            <button type="button" class="btn btn-fa pand_back" p-id="<%= @order.id %>">审核驳回</button>
          <% end %>
          <% if @order.passed? && can_access("仓库") %>
            <button type="button" class="btn btn-stm to_deliver" p-id="<%= @order.id %>">发货</button>
            <button type="button" class="btn btn-stm pand_back" p-id="<%= @order.id %>">物流驳回</button>
          <% end %>
          <% if @order.delivered? && can_access("仓库") %>
            <%= link_to "打印", print_order_order_path(@order), class: "btn btn-stm", style:"color: #FFF;" %>
          <% end %>
          <% if @order.may_cancel? && can_access("前台客服") %>
            <button type="button" class="btn btn-cs to_cancel" p-id="<%= @order.id %>">作废</button>
          <% end %>
        </div>
      </div>
    </div>

    <% if @order.pandding_logs.count > 0 %>
      <div class="page-header">
        <h4>驳回日志</h4>
      </div>
      <div class="jumbotron">
        <table class="table table-condensed table-bordered table-hover">
          <thead>
            <tr>
              <th></th>
              <th>驳回时间</th>
              <th>驳回人</th>
              <th>驳回理由</th>
            </tr>
          </thead>

          <tbody>
            <% index = 1%>
            <% @order.pandding_logs.order("id desc").each do |l| %>
              <tr>
                <td><%= index %></td>
                <td><%= l.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
                <td><%= "#{l.user.name} <#{l.user.roles.join("、")}>" %></td>
                <td><%= l.reason %></td>
              </tr>
              <% index += 1 %>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
  // params
  var totle_sum = "<%= @order.totle_sum %>"
</script>