config/routes.rb
Rails.application.routes.draw do

  resources :panding_logs

  resources :products#, except: [:destroy]

  resources :order_details

  resources :customers, except: [:destroy]

  resources :orders do
    member do
      post 'to_pand'
      post 'pand_pass'
      post 'pand_back'
      post 'to_deliver'
      post 'to_cancel'
      get 'print_order'
      get 'fancybox_show'
    end
  end

  root 'welcome#index'

  resources :users, only: [:index, :show, :edit, :update, :new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def is_admin?
    unless current_user.is? "系统管理员"
      flash[:notice] = "您的权限不足，请联系系统管理员，谢谢！"
      redirect_to '/' 
    end
    true
  end

  def can_access role
    if current_user.is? role
      true
    else
      is_admin?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_access role
    current_user.is?(role) || current_user.is?("系统管理员")
  end
end

app/views/application/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid" style="padding-left: 10%; padding-right: 10%;">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to '订单管理系统', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "用户列表", users_path %></li>
        <li><%= link_to "订单列表", orders_path %></li>
        <li><%= link_to "客户列表", customers_path %></li>
        <li><%= link_to "产品列表", products_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "#{current_user.name} <#{current_user.roles.join("、")}>", user_path(current_user) %></li>
          <li><%= link_to "退出", '/logout' %></li>
        <% else %>
          <li><%= link_to '登录', '/login' %></li>
          <li><%= link_to '注册', '/signup' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>