config/routes.rb
Rails.application.routes.draw do

  resources :panding_logs

  resources :products#, except: [:destroy]

  resources :order_details

  resources :customers, except: [:destroy]

  resources :orders do
    member do
      post 'to_pand'
      post 'pand_pass'
      post 'pand_back'
      post 'to_deliver'
      post 'to_cancel'
      get 'print_order'
      get 'fancybox_show'
    end
  end

  root 'welcome#index'

  resources :users, only: [:index, :show, :edit, :update, :new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include AASM

  has_many :order_details

  validates_presence_of :name
  validates_presence_of :unit
  validates_presence_of :price
  validates_uniqueness_of :name

  scope :published, -> {
    where(aasm_state: "published")
  }

  STATE_HASH = {
    published: "可用",
    deleted: "已删除"
  }.freeze

  aasm do
    state :published, :initial => true
    state :deleted

    # 删除产品
    event :offline do
      transitions :from => :published, :to => :deleted
    end

    # 恢复删除的产品
    event :online do
      transitions :from => :deleted, :to => :published
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page])
    # @products = Product.page(params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.offline!
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :unit, :price, :aasm_state)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {class: "form-horizontal"}) do |f| %>
  <% if @product.errors.any? %>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <div class="alert alert-warning alert-danger" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4><%= @product.errors.count %>个错误导致保存失败:</h4>
          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
  <% end %>

  <div class="form-group">
    <label for="product_name" class="col-sm-2 control-label">产品名称及规格</label>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="product_unit" class="col-sm-2 control-label">产品单位</label>
    <div class="col-sm-8">
      <%= f.text_field :unit, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="product_price" class="col-sm-2 control-label">产品单价</label>
    <div class="col-sm-8">
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <label for="product_price" class="col-sm-2 control-label">产品状态</label>
    <div class="col-sm-8">
      <%= f.select :aasm_state, Product::STATE_HASH.invert, {}, class: "form-control" %>
    </div>
    <div class="col-sm-2"></div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>更新产品信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '产品详情', @product, class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '返回产品列表', products_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>产品信息列表</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '新建产品', new_product_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= search_form_for @q, class: "form-inline", html: {style: "margin-bottom: 10px;"} do |f| %>
      <div class="form-group">
        <label class="sr-only" for="q_name_cont"></label>
        <%= f.search_field :name_cont, class: "form-control", placeholder: "产品名称及规格" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_unit_cont"></label>
        <%= f.search_field :unit_cont, class: "form-control", placeholder: "产品单位" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_price_gteq"></label>
        <%= f.search_field :price_gteq, class: "form-control", placeholder: "产品单价大于等于" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_price_lteq"></label>
        <%= f.search_field :price_lteq, class: "form-control", placeholder: "产品单价小于等于" %>
      </div>

      <div class="form-group">
        <label class="sr-only" for="q_pass_time_lteq"></label>
        <%= f.select :aasm_state_eq, options_for_select(Product::STATE_HASH.invert, @q.aasm_state_eq), {include_blank: "请选择状态"}, {:class => 'form-control'} %>
      </div>

      <button type="submit" class="btn btn-primary">查询</button>
      <button type="submit" id="search_reset" class="btn btn-warning">重置</button>
    <% end %>

    <table class="table table-condensed table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>产品名称及规格</th>
          <th>产品单位</th>
          <th>产品单价</th>
          <th>操作</th> 
        </tr>
      </thead>
      <tbody>
        <% @products.each do |u| %>
          <tr>
            <td><%= u.id %></td>
            <td><%= u.name %></td>
            <td><%= u.unit %></td>
            <td><%= u.price %></td>
            <td>
              <%= link_to "查看产品详情", product_path(u), class: "btn btn-default" %>
              <%= link_to "更改产品信息", edit_product_path(u), class: "btn btn-default" %>
              <% if u.may_offline? %>
                <%= link_to '删除产品', product_path(u), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              <% end %>
            </td> 
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @products %>
  </div>
  <div class="col-md-1"></div>
</div>

<script type="text/javascript">
  // controller & action
  var current_controller = "<%= params[:controller] %>";
  var current_action = "<%= params[:action] %>";
</script>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>创建产品信息</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '返回产品列表', products_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <div class="row">
        <div class="col-md-6">
          <h3>产品信息详情</h3>
        </div>
        <div class="col-md-6" style='text-align: right;'>
          <%= link_to '新建产品', new_product_path, class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '编辑产品', edit_product_path(@product), class: "btn btn-default", style: "margin-top: 20px;" %>
          <%= link_to '返回产品列表', products_path, class: "btn btn-default", style: "margin-top: 20px;" %>
        </div>
      </div>
    </div>

    <div class="jumbotron">
      <table class="table">
        <tr>
          <td>产品名称及规格：</td>
          <td><%= @product.name %></td>
        </tr>

        <tr>
          <td>产品单位：</td>
          <td><%= @product.unit %></td>
        </tr>

        <tr>
          <td>产品单价：</td>
          <td><%= @product.price %></td>
        </tr>

        <tr>
          <td>产品状态：</td>
          <td><%= Product::STATE_HASH[@product.aasm_state.to_sym] %></td>
        </tr>
      </table>
    </div>

  </div>
  <div class="col-md-1"></div>
</div>